version: '3.8'
services:
  server:
    container_name: backendcontainer
    image: springimg
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresdatabase
  postgresdatabase:
    container_name: postgrescontainer
    image: library/postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=************
      - POSTGRES_USER=postgres
      - POSTGRES_DB=city-db
